In \[1\]:

    import numpy as np
    import pandas as pd
    import folium
    import json
    import matplotlib.pyplot as plt
    import seaborn as sns

In \[16\]:

    gas_station_df=pd.read_excel("score_gas station_loc.xlsx")

In \[17\]:

    gas_station_df.head()

Out\[17\]:

|     | 법정동 | 주소                                                  |
|-----|--------|-------------------------------------------------------|
| 0   | 화곡동 | 서울특별시 강서구 공항대로 432(화곡6동 1125)화곡동    |
| 1   | 화곡동 | 서울특별시 강서구 화곡로 273(화곡6동 983-1)화곡동     |
| 2   | 화곡동 | 서울특별시 강서구 국회대로 225(화곡4동 843-4)화곡동   |
| 3   | 화곡동 | 서울특별시 강서구 국회대로 71(화곡1동 931-11)화곡동   |
| 4   | 화곡동 | 서울특별시 강서구 곰달래로 207( 화곡2동 862-16)화곡동 |

In \[18\]:

    import time
    import requests, json
    import pandas as pd

In \[19\]:

    def get_location(addr):
        url = 'https://dapi.kakao.com/v2/local/search/address.json?query={address}'.format(address=addr)
        headers = {"Authorization": "KakaoAK 1b95761d8139e76e42c6627512e127b7"}
        result = json.loads(str(requests.get(url, headers=headers).text))
        match_first = result['documents'][0]['address']
        return float(match_first['x']), float(match_first['y'])

In \[20\]:

    get_location('서울 중구 회현동1가')

Out\[20\]:

    (126.981204133005, 37.5555892070291)

In \[21\]:

    latitude = []
    longitude = []
    address = gas['주소']

In \[22\]:

    print(len(address))
    address.head()

    25

Out\[22\]:

    0       서울특별시 강서구 공항대로 432(화곡6동 1125)화곡동
    1       서울특별시 강서구 화곡로 273(화곡6동 983-1)화곡동
    2      서울특별시 강서구 국회대로 225(화곡4동 843-4)화곡동
    3      서울특별시 강서구 국회대로 71(화곡1동 931-11)화곡동
    4    서울특별시 강서구 곰달래로 207( 화곡2동 862-16)화곡동
    Name: 주소, dtype: object

In \[33\]:

    import pandas as pd
    import math

    # 주유소 데이터 로드
    gas_station_df = pd.read_excel("score_gas station_xy.xlsx")
    elec_station_df = pd.read_excel("elec_station.xlsx")

In \[34\]:

    gas_station_df

Out\[34\]:

|     | 법정동 | 주소                                                       | Latitude  | Longitude  |
|-----|--------|------------------------------------------------------------|-----------|------------|
| 0   | 화곡동 | 서울특별시 강서구 공항대로 432(화곡6동 1125)화곡동         | 37.554668 | 126.854805 |
| 1   | 화곡동 | 서울특별시 강서구 화곡로 273(화곡6동 983-1)화곡동          | 37.549163 | 126.846996 |
| 2   | 화곡동 | 서울특별시 강서구 국회대로 225(화곡4동 843-4)화곡동        | 37.529621 | 126.859797 |
| 3   | 화곡동 | 서울특별시 강서구 국회대로 71(화곡1동 931-11)화곡동        | 37.527258 | 126.842890 |
| 4   | 화곡동 | 서울특별시 강서구 곰달래로 207( 화곡2동 862-16)화곡동      | 37.531580 | 126.856052 |
| 5   | 화곡동 | 서울특별시 강서구 국회대로 251(화곡4동 785-2)화곡동        | 37.530040 | 126.862983 |
| 6   | 화곡동 | 서울특별시 강서구 강서로 151(화곡1동 402-1)화곡동          | 37.540261 | 126.841198 |
| 7   | 화곡동 | 서울특별시 강서구 강서로 154(화곡본동 1076-14)화곡동       | 37.540719 | 126.841530 |
| 8   | 봉천동 | 서울특별시 관악구 남부순환로 1920 (인헌동 1659-1)봉천동    | 37.476547 | 126.962648 |
| 9   | 봉천동 | 서울특별시 관악구 남부순환로 1691 (은천동 948-17)봉천동    | 37.486514 | 126.941524 |
| 10  | 봉천동 | 서울특별시 관악구 남부순환로 1753 (은천동 912-15)봉천동    | 37.486514 | 126.941524 |
| 11  | 봉천동 | 서울특별시 관악구 남부순환로 1883 (행운동 1679-30)봉천동   | 37.481060 | 126.960857 |
| 12  | 봉천동 | 서울특별시 관악구 보라매로 41 (보라매동 726-10)봉천동      | 37.493202 | 126.926737 |
| 13  | 봉천동 | 서울특별시 관악구 남부순환로 1880 (낙성대동 1663-11)봉천동 | 37.474160 | 126.958181 |
| 14  | 봉천동 | 서울특별시 관악구 보라매로 26 (보라매동 729-4)봉천동       | 37.491687 | 126.927160 |
| 15  | 신림동 | 서울특별시 관악구 난곡로 206 (난곡동 616-1)신림동          | 37.473410 | 126.918793 |
| 16  | 신림동 | 서울특별시 관악구 신림로 290 (서원동 1641-58)신림동        | 37.486790 | 126.927611 |
| 17  | 신림동 | 서울특별시 관악구 난곡로 108 (난향동 666-14)신림동         | 37.461990 | 126.918499 |
| 18  | 신림동 | 서울특별시 관악구 문성로 97 (미성동 1477-5)신림동          | 37.477794 | 126.914302 |
| 19  | 신림동 | 서울특별시 관악구 남부순환로 1520 (미성동 1571-8)신림동    | 37.476024 | 126.915989 |
| 20  | 신림동 | 서울특별시 관악구 신림로 176 (서림동 112-47)신림동         | 37.473627 | 126.938828 |
| 21  | 신림동 | 서울특별시 관악구 남부순환로 1515 (신사동 507-24)신림동    | 37.485691 | 126.918659 |
| 22  | 상계동 | 서울특별시 노원구 노원로26길 191(상계동)상계동             | 37.658394 | 127.071138 |
| 23  | 상계동 | 서울특별시 노원구 노해로 527(상계동)상계동                 | 37.655939 | 127.066406 |
| 24  | 상계동 | 서울특별시 노원구 동일로 1772(상계동)상계동                | 37.686659 | 127.055818 |

In \[35\]:

    elec_station_df

Out\[35\]:

|     | 주소                                                                           | Latitude  | Longitude  | 법정동 |
|-----|--------------------------------------------------------------------------------|-----------|------------|--------|
| 0   | 서울특별시 강서구 화곡동 가로공원로                                            | 37.537366 | 126.838674 | 화곡동 |
| 1   | 서울특별시 강서구 화곡동 곰달래문화복지                                        | 37.528901 | 126.848813 | 화곡동 |
| 2   | 서울특별시 관악구 봉천로21길 38, 입구좌측, 지하 각 1기                         | 37.488580 | 126.934496 | 봉천동 |
| 3   | 서울특별시 관악구 관악로 96(봉천동 1594-8)                                     | 37.473726 | 126.953472 | 봉천동 |
| 4   | 서울특별시 관악구 관악로 282, 주차장(봉천동 9-15)                              | 37.489070 | 126.958014 | 봉천동 |
| 5   | 서울특별시 관악구 청룡1길 34 (봉천동, KT관악지점)                              | 37.481512 | 126.948419 | 봉천동 |
| 6   | 서울특별시 관악구 행운10길 21(봉천동, 관악파크푸르지오아파트)(1728 관악파크... | 37.482920 | 126.961292 | 봉천동 |
| 7   | 서울특별시 관악구 관악로30길 12(봉천동, 관악우성아파트)(1706 관악우성아파트)   | 37.485544 | 126.959640 | 봉천동 |
| 8   | 서울특별시 관악구 남부순환로 1924(봉천동, 동림오피스텔) 지하주차장(1659-4...   | 37.483513 | 126.955117 | 봉천동 |
| 9   | 서울특별시 관악구 성현로 80, 관악드림타운아파트(1712 관악드림타운아파트)       | 37.489754 | 126.950507 | 봉천동 |
| 10  | 서울특별시 관악구 쑥고개로 100(봉천동 1574-1)                                  | 37.478918 | 126.947724 | 봉천동 |
| 11  | 서울특별시 관악구 봉천로 472(봉천동 861-7)                                     | 37.481888 | 126.952208 | 봉천동 |
| 12  | 서울특별시 관악구 낙성대로3길 11, 삼이택시(봉천동 213-4)                       | 37.475462 | 126.960057 | 봉천동 |
| 13  | 서울특별시 관악구 관악로 133(봉천동 1701)                                      | 37.477063 | 126.951890 | 봉천동 |
| 14  | 서울특별시 관악구 남부순환로 1675, 기아 서울대대리점(봉천동 958-13)            | 37.484811 | 126.936970 | 봉천동 |
| 15  | 서울특별시 관악구 봉천로 294, 주차장(신림동 1415-1)                            | 37.486611 | 126.933371 | 신림동 |
| 16  | 서울특별시 관악구 난향3길 22, 주차장(신림동 673-45)                            | 37.462278 | 126.916736 | 신림동 |
| 17  | 서울특별시 관악구 신림로36길 24-5, 주차장(신림동 94-89)                        | 37.475677 | 126.938808 | 신림동 |
| 18  | 서울특별시 관악구 조원중앙로1길 26 (신림동 KT구로지사)주차장                   | 37.480822 | 126.902813 | 신림동 |
| 19  | 서울특별시 관악구 호암로 519(신림동, 벽산블루밍아파트)(1733 벽산블루밍아파트)  | 37.463728 | 126.931106 | 신림동 |
| 20  | 서울특별시 관악구 신원로3길 13(신림동)(신원동 복합청사)                        | 37.481572 | 126.927338 | 신림동 |
| 21  | 서울특별시 관악구 신사로 114(신림동 498-55)                                    | 37.487760 | 126.914888 | 신림동 |
| 22  | 서울특별시 관악구 난곡로 220(신림동)(신림동 607-73)                            | 37.474326 | 126.917979 | 신림동 |
| 23  | 서울특별시 관악구 신원로 26(1695 신림동부아파트)                               | 37.480433 | 126.929255 | 신림동 |
| 24  | 서울특별시 관악구 난곡로 374, 주차장(신림동 516)                               | 37.487212 | 126.913398 | 신림동 |
| 25  | 서울특별시 관악구 난곡로 80, B1,B3(신림SH Ville아파트 B1,B3)                   | 37.462466 | 126.919809 | 신림동 |
| 26  | 서울특별시 관악구 조원로 142, 지하1층(신림동 492-4 지하1층)                    | 37.485421 | 126.918106 | 신림동 |
| 27  | 서울특별시 관악구 호암로26길 64(신림동 1518-2)                                 | 37.470185 | 126.937183 | 신림동 |
| 28  | 서울특별시 관악구 남부순환로 1395, 기아 토리대리점(신림동 572-5)               | 37.486790 | 126.927611 | 신림동 |
| 29  | 서울특별시 관악구 관천로17길 6-1(신림동 460-9)                                 | 37.487452 | 126.921820 | 신림동 |
| 30  | 서울특별시 노원구 덕릉로 450                                                   | 37.644160 | 127.058300 | 상계동 |
| 31  | 서울특별시 노원구 상계2동 373-13                                               | 37.656471 | 127.066249 | 상계동 |
| 32  | 서울특별시 노원구 상계동 65-40                                                 | 37.667819 | 127.076949 | 상계동 |
| 33  | 서울특별시 노원구 동일로1107                                                   | 37.628529 | 127.071096 | 상계동 |
| 34  | 서울특별시 노원구 마들로3길 15                                                 | 37.627340 | 127.061858 | 상계동 |
| 35  | 서울특별시 노원구 노원로 530                                                   | 37.661265 | 127.060253 | 상계동 |
| 36  | 서울특별시 노원구 한글비석로 434                                               | 37.662951 | 127.069363 | 상계동 |
| 37  | 서울특별시 노원구 상계동 노원도봉지사                                          | 37.678695 | 127.053407 | 상계동 |
| 38  | 서울특별시 노원구 상계동 상계성원아파트                                        | 37.660331 | 127.065764 | 상계동 |
| 39  | 서울특별시 노원구 상계동 상계우방아파트                                        | 37.671912 | 127.056653 | 상계동 |
| 40  | 서울특별시 노원구 상계동 아이파크아파트                                        | 37.623502 | 127.083041 | 상계동 |
| 41  | 서울특별시 노원구 상계동 우림루머아트                                          | 37.675642 | 127.055916 | 상계동 |
| 42  | 서울특별시 노원구 상계동 상계금호타운                                          | 37.672991 | 127.070350 | 상계동 |
| 43  | 서울특별시 노원구 상계동 불암대림아파트                                        | 37.663628 | 127.076177 | 상계동 |
| 44  | 서울특별시 노원구 상계동 노원센트럴푸르지오                                    | 37.664263 | 127.074622 | 상계동 |
| 45  | 서울특별시 노원구 상계동 케이티노원빌딩                                        | 37.656520 | 127.063266 | 상계동 |
| 46  | 서울특별시 노원구 상계동 상계주공아파트                                        | 37.650310 | 127.066641 | 상계동 |
| 47  | 서울특별시 노원구 상계동 수락산디자인거리 공영주차장                           | 37.674897 | 127.057727 | 상계동 |
| 48  | 서울특별시 노원구 상계동 상계한신아파트                                        | 37.664330 | 127.067319 | 상계동 |
| 49  | 서울특별시 노원구 상계동 노원구청                                              | 37.654078 | 127.056605 | 상계동 |
| 50  | 서울특별시 노원구 상계동 서울신상계초등학교                                    | 37.667474 | 127.075790 | 상계동 |
| 51  | 서울특별시 노원구 상계동 노원 포레나노아파트                                   | 37.654527 | 127.060551 | 상계동 |
| 52  | 서울특별시 노원구 상계동 일성운수                                              | 37.683744 | 127.053125 | 상계동 |
| 53  | 서울특별시 노원구 상계동 노원청암아파트                                        | 37.654527 | 127.060551 | 상계동 |
| 54  | 서울특별시 노원구 상계동 상계동양메이저아파트                                  | 37.657470 | 127.064014 | 상계동 |
| 55  | 서울특별시 노원구 상계동 케이티노원빌딩                                        | 37.656520 | 127.063266 | 상계동 |

In \[36\]:

    # 비행 금지 구역 좌표 설정
    forbidden_area_centers = [(37.3209, 126.5838), (37.3232, 126.5943)]
    forbidden_area_radius = 3.7  # 단위: km

    # 두 지점 간의 하버사인 거리 계산 함수
    def haversine_distance(lat1, lon1, lat2, lon2):
        R = 6371  # 지구 반지름 (단위: km)
        dlat = math.radians(lat2 - lat1)
        dlon = math.radians(lon2 - lon1)
        a = math.sin(dlat / 2) ** 2 + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon / 2) ** 2
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
        distance = R * c
        return distance

    # 비행 금지 구역 내에 있는 주유소 제외한 데이터프레임 생성
    filtered_gas_station_df = gas_station_df.copy()
    for center in forbidden_area_centers:
        lat_center, lon_center = center
        filtered_gas_station_df = filtered_gas_station_df[filtered_gas_station_df.apply(
            lambda row: haversine_distance(row["Latitude"], row["Longitude"], lat_center, lon_center) > forbidden_area_radius,
            axis=1
        )]

    # 결과 출력
    print(filtered_gas_station_df)

        법정동                                      주소   Latitude   Longitude
    0   화곡동        서울특별시 강서구 공항대로 432(화곡6동 1125)화곡동  37.554668  126.854805
    1   화곡동        서울특별시 강서구 화곡로 273(화곡6동 983-1)화곡동  37.549163  126.846996
    2   화곡동       서울특별시 강서구 국회대로 225(화곡4동 843-4)화곡동  37.529621  126.859797
    3   화곡동       서울특별시 강서구 국회대로 71(화곡1동 931-11)화곡동  37.527258  126.842890
    4   화곡동     서울특별시 강서구 곰달래로 207( 화곡2동 862-16)화곡동  37.531580  126.856052
    5   화곡동       서울특별시 강서구 국회대로 251(화곡4동 785-2)화곡동  37.530040  126.862983
    6   화곡동        서울특별시 강서구 강서로 151(화곡1동 402-1)화곡동  37.540261  126.841198
    7   화곡동      서울특별시 강서구 강서로 154(화곡본동 1076-14)화곡동  37.540719  126.841530
    8   봉천동    서울특별시 관악구 남부순환로 1920 (인헌동 1659-1)봉천동  37.476547  126.962648
    9   봉천동    서울특별시 관악구 남부순환로 1691 (은천동 948-17)봉천동  37.486514  126.941524
    10  봉천동    서울특별시 관악구 남부순환로 1753 (은천동 912-15)봉천동  37.486514  126.941524
    11  봉천동   서울특별시 관악구 남부순환로 1883 (행운동 1679-30)봉천동  37.481060  126.960857
    12  봉천동      서울특별시 관악구 보라매로 41 (보라매동 726-10)봉천동  37.493202  126.926737
    13  봉천동  서울특별시 관악구 남부순환로 1880 (낙성대동 1663-11)봉천동  37.474160  126.958181
    14  봉천동       서울특별시 관악구 보라매로 26 (보라매동 729-4)봉천동  37.491687  126.927160
    15  신림동        서울특별시 관악구 난곡로 206 (난곡동 616-1)신림동  37.473410  126.918793
    16  신림동      서울특별시 관악구 신림로 290 (서원동 1641-58)신림동  37.486790  126.927611
    17  신림동       서울특별시 관악구 난곡로 108 (난향동 666-14)신림동  37.461990  126.918499
    18  신림동        서울특별시 관악구 문성로 97 (미성동 1477-5)신림동  37.477794  126.914302
    19  신림동    서울특별시 관악구 남부순환로 1520 (미성동 1571-8)신림동  37.476024  126.915989
    20  신림동       서울특별시 관악구 신림로 176 (서림동 112-47)신림동  37.473627  126.938828
    21  신림동    서울특별시 관악구 남부순환로 1515 (신사동 507-24)신림동  37.485691  126.918659
    22  상계동            서울특별시 노원구 노원로26길 191(상계동)상계동  37.658394  127.071138
    23  상계동               서울특별시 노원구 노해로 527(상계동)상계동  37.655939  127.066406
    24  상계동              서울특별시 노원구 동일로 1772(상계동)상계동  37.686659  127.055818

In \[45\]:

    # 두 지점 간의 하버사인 거리 계산 함수
    def haversine_distance(lat1, lon1, lat2, lon2):
        R = 6371  # 지구 반지름 (단위: km)
        dlat = math.radians(lat2 - lat1)
        dlon = math.radians(lon2 - lon1)
        a = math.sin(dlat / 2) ** 2 + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon / 2) ** 2
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
        distance = R * c
        return distance

    # 가장 가까운 충전소 거리 계산
    gas_station_df["dis_elec"] = float('inf')  # 초기값으로 무한대 설정
    for _, elec_row in elec_station_df.iterrows():
        elec_lat, elec_lon = elec_row["Latitude"], elec_row["Longitude"]
        gas_station_df["Distance"] = gas_station_df.apply(
            lambda row: haversine_distance(row["Latitude"], row["Longitude"], elec_lat, elec_lon),
            axis=1
        )
        gas_station_df["dis_elec"] = gas_station_df[["dis_elec", "Distance"]].min(axis=1)

    # 결과 출력
    result_df = gas_station_df[["법정동", "Latitude", "Longitude", "dis_elec"]].copy()
    result_df

Out\[45\]:

|     | 법정동 | Latitude  | Longitude  | dis_elec |
|-----|--------|-----------|------------|----------|
| 0   | 화곡동 | 37.554668 | 126.854805 | 2.392421 |
| 1   | 화곡동 | 37.549163 | 126.846996 | 1.503003 |
| 2   | 화곡동 | 37.529621 | 126.859797 | 0.971863 |
| 3   | 화곡동 | 37.527258 | 126.842890 | 0.553404 |
| 4   | 화곡동 | 37.531580 | 126.856052 | 0.704420 |
| 5   | 화곡동 | 37.530040 | 126.862983 | 1.255868 |
| 6   | 화곡동 | 37.540261 | 126.841198 | 0.391365 |
| 7   | 화곡동 | 37.540719 | 126.841530 | 0.449855 |
| 8   | 봉천동 | 37.476547 | 126.962648 | 0.258459 |
| 9   | 봉천동 | 37.486514 | 126.941524 | 0.444271 |
| 10  | 봉천동 | 37.486514 | 126.941524 | 0.444271 |
| 11  | 봉천동 | 37.481060 | 126.960857 | 0.210314 |
| 12  | 봉천동 | 37.493202 | 126.926737 | 0.717156 |
| 13  | 봉천동 | 37.474160 | 126.958181 | 0.219920 |
| 14  | 봉천동 | 37.491687 | 126.927160 | 0.546051 |
| 15  | 신림동 | 37.473410 | 126.918793 | 0.124683 |
| 16  | 신림동 | 37.486790 | 126.927611 | 0.000000 |
| 17  | 신림동 | 37.461990 | 126.918499 | 0.127155 |
| 18  | 신림동 | 37.477794 | 126.914302 | 0.503953 |
| 19  | 신림동 | 37.476024 | 126.915989 | 0.257848 |
| 20  | 신림동 | 37.473627 | 126.938828 | 0.227901 |
| 21  | 신림동 | 37.485691 | 126.918659 | 0.057297 |
| 22  | 상계동 | 37.658394 | 127.071138 | 0.480492 |
| 23  | 상계동 | 37.655939 | 127.066406 | 0.060736 |
| 24  | 상계동 | 37.686659 | 127.055818 | 0.401524 |

In \[47\]:

    import pandas as pd
    import math

    # 주유소 데이터 로드
    gas_station_df = pd.read_excel("score_gas station_xy.xlsx")
    mail_address_df = pd.read_excel("mail_address.xlsx")

    # 두 지점 간의 하버사인 거리 계산 함수
    def haversine_distance(lat1, lon1, lat2, lon2):
        R = 6371  # 지구 반지름 (단위: km)
        dlat = math.radians(lat2 - lat1)
        dlon = math.radians(lon2 - lon1)
        a = math.sin(dlat / 2) ** 2 + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon / 2) ** 2
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
        distance = R * c
        return distance

    # 가장 가까운 충전소 거리 계산
    gas_station_df["dis_elec"] = float('inf')  # 초기값으로 무한대 설정
    for _, elec_row in elec_station_df.iterrows():
        elec_lat, elec_lon = elec_row["Latitude"], elec_row["Longitude"]
        gas_station_df["Distance"] = gas_station_df.apply(
            lambda row: haversine_distance(row["Latitude"], row["Longitude"], elec_lat, elec_lon),
            axis=1
        )
        gas_station_df["dis_elec"] = gas_station_df[["dis_elec", "Distance"]].min(axis=1)

    # 가장 가까운 충전소와 메일 주소 거리 계산
    gas_station_df["dis_address"] = float('inf')  # 초기값으로 무한대 설정
    for _, address_row in mail_address_df.iterrows():
        address_lat, address_lon = address_row["Latitude"], address_row["Longitude"]
        gas_station_df["dis_gas"] = gas_station_df.apply(
            lambda row: haversine_distance(row["Latitude"], row["Longitude"], address_lat, address_lon),
            axis=1
        )
        gas_station_df["dis_address"] = gas_station_df[["dis_address", "dis_gas"]].min(axis=1)

    # 결과 출력
    result_df = gas_station_df[["법정동", "Latitude", "Longitude", "dis_elec", "dis_address"]].copy()
    print(result_df)

        법정동   Latitude   Longitude  dis_elec  dis_address
    0   화곡동  37.554668  126.854805  2.392421     0.583660
    1   화곡동  37.549163  126.846996  1.503003     0.450540
    2   화곡동  37.529621  126.859797  0.971863     0.527042
    3   화곡동  37.527258  126.842890  0.553404     0.533816
    4   화곡동  37.531580  126.856052  0.704420     0.138499
    5   화곡동  37.530040  126.862983  1.255868     0.551146
    6   화곡동  37.540261  126.841198  0.391365     0.325201
    7   화곡동  37.540719  126.841530  0.449855     0.274768
    8   봉천동  37.476547  126.962648  0.258459     0.285818
    9   봉천동  37.486514  126.941524  0.444271     0.514397
    10  봉천동  37.486514  126.941524  0.444271     0.514397
    11  봉천동  37.481060  126.960857  0.210314     0.340756
    12  봉천동  37.493202  126.926737  0.717156     1.050450
    13  봉천동  37.474160  126.958181  0.219920     0.638931
    14  봉천동  37.491687  126.927160  0.546051     0.955026
    15  신림동  37.473410  126.918793  0.124683     0.582609
    16  신림동  37.486790  126.927611  0.000000     0.756466
    17  신림동  37.461990  126.918499  0.127155     1.739584
    18  신림동  37.477794  126.914302  0.503953     0.175620
    19  신림동  37.476024  126.915989  0.257848     0.246384
    20  신림동  37.473627  126.938828  0.227901     0.239308
    21  신림동  37.485691  126.918659  0.057297     0.048775
    22  상계동  37.658394  127.071138  0.480492     0.305428
    23  상계동  37.655939  127.066406  0.060736     0.214360
    24  상계동  37.686659  127.055818  0.401524     0.979209

In \[52\]:

    import pandas as pd
    import math

    # 주유소 데이터 로드
    gas_station_df = pd.read_excel("score_gas station_xy.xlsx")
    mail_address_df = pd.read_excel("mail_address.xlsx")

    # 두 지점 간의 하버사인 거리 계산 함수
    def haversine_distance(lat1, lon1, lat2, lon2):
        R = 6371  # 지구 반지름 (단위: km)
        dlat = math.radians(lat2 - lat1)
        dlon = math.radians(lon2 - lon1)
        a = math.sin(dlat / 2) ** 2 + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon / 2) ** 2
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
        distance = R * c
        return distance

    # 가장 가까운 충전소 거리 계산
    gas_station_df["dis_elec"] = float('inf')  # 초기값으로 무한대 설정
    for _, elec_row in elec_station_df.iterrows():
        elec_lat, elec_lon = elec_row["Latitude"], elec_row["Longitude"]
        gas_station_df["Distance"] = gas_station_df.apply(
            lambda row: haversine_distance(row["Latitude"], row["Longitude"], elec_lat, elec_lon),
            axis=1
        )
        gas_station_df["dis_elec"] = gas_station_df[["dis_elec", "Distance"]].min(axis=1)

    # 가장 가까운 충전소와 메일 주소 거리 계산
    gas_station_df["dis_address"] = float('inf')  # 초기값으로 무한대 설정
    for _, address_row in mail_address_df.iterrows():
        address_lat, address_lon = address_row["Latitude"], address_row["Longitude"]
        gas_station_df["dis_gas"] = gas_station_df.apply(
            lambda row: haversine_distance(row["Latitude"], row["Longitude"], address_lat, address_lon),
            axis=1
        )
        gas_station_df["dis_address"] = gas_station_df[["dis_address", "dis_gas"]].min(axis=1)

    # 결과 추가
    result_df["dis_elec"] = gas_station_df["dis_elec"]
    result_df["dis_address"] = gas_station_df["dis_address"]

    print(result_df)

        법정동   Latitude   Longitude   dis_bike  dis_elec  dis_address
    0   화곡동  37.554668  126.854805   0.629078  2.392421     0.583660
    1   화곡동  37.549163  126.846996   0.295716  1.503003     0.450540
    2   화곡동  37.529621  126.859797   0.389992  0.971863     0.527042
    3   화곡동  37.527258  126.842890   0.493867  0.553404     0.533816
    4   화곡동  37.531580  126.856052   0.666669  0.704420     0.138499
    5   화곡동  37.530040  126.862983   0.160850  1.255868     0.551146
    6   화곡동  37.540261  126.841198   0.154077  0.391365     0.325201
    7   화곡동  37.540719  126.841530   0.138532  0.449855     0.274768
    8   봉천동  37.476547  126.962648  10.654848  0.258459     0.285818
    9   봉천동  37.486514  126.941524   8.493601  0.444271     0.514397
    10  봉천동  37.486514  126.941524   8.493601  0.444271     0.514397
    11  봉천동  37.481060  126.960857  10.242812  0.210314     0.340756
    12  봉천동  37.493202  126.926737   7.002997  0.717156     1.050450
    13  봉천동  37.474160  126.958181  10.493184  0.219920     0.638931
    14  봉천동  37.491687  126.927160   7.135752  0.546051     0.955026
    15  신림동  37.473410  126.918793   8.079294  0.124683     0.582609
    16  신림동  37.486790  126.927611   7.514963  0.000000     0.756466
    17  신림동  37.461990  126.918499   9.111208  0.127155     1.739584
    18  신림동  37.477794  126.914302   7.451469  0.503953     0.175620
    19  신림동  37.476024  126.915989   7.698220  0.257848     0.246384
    20  신림동  37.473627  126.938828   9.235526  0.227901     0.239308
    21  신림동  37.485691  126.918659   7.029246  0.057297     0.048775
    22  상계동  37.658394  127.071138   0.086559  0.480492     0.305428
    23  상계동  37.655939  127.066406   0.097205  0.060736     0.214360
    24  상계동  37.686659  127.055818   0.263639  0.401524     0.979209

In \[54\]:

    result_df["sum_dis"] = result_df["dis_bike"] + result_df["dis_elec"] + result_df["dis_address"]
    print(result_df)

        법정동   Latitude   Longitude   dis_bike  dis_elec  dis_address    sum_dis
    0   화곡동  37.554668  126.854805   0.629078  2.392421     0.583660   3.605158
    1   화곡동  37.549163  126.846996   0.295716  1.503003     0.450540   2.249258
    2   화곡동  37.529621  126.859797   0.389992  0.971863     0.527042   1.888897
    3   화곡동  37.527258  126.842890   0.493867  0.553404     0.533816   1.581088
    4   화곡동  37.531580  126.856052   0.666669  0.704420     0.138499   1.509588
    5   화곡동  37.530040  126.862983   0.160850  1.255868     0.551146   1.967864
    6   화곡동  37.540261  126.841198   0.154077  0.391365     0.325201   0.870643
    7   화곡동  37.540719  126.841530   0.138532  0.449855     0.274768   0.863156
    8   봉천동  37.476547  126.962648  10.654848  0.258459     0.285818  11.199125
    9   봉천동  37.486514  126.941524   8.493601  0.444271     0.514397   9.452269
    10  봉천동  37.486514  126.941524   8.493601  0.444271     0.514397   9.452269
    11  봉천동  37.481060  126.960857  10.242812  0.210314     0.340756  10.793883
    12  봉천동  37.493202  126.926737   7.002997  0.717156     1.050450   8.770603
    13  봉천동  37.474160  126.958181  10.493184  0.219920     0.638931  11.352035
    14  봉천동  37.491687  126.927160   7.135752  0.546051     0.955026   8.636829
    15  신림동  37.473410  126.918793   8.079294  0.124683     0.582609   8.786585
    16  신림동  37.486790  126.927611   7.514963  0.000000     0.756466   8.271429
    17  신림동  37.461990  126.918499   9.111208  0.127155     1.739584  10.977947
    18  신림동  37.477794  126.914302   7.451469  0.503953     0.175620   8.131042
    19  신림동  37.476024  126.915989   7.698220  0.257848     0.246384   8.202453
    20  신림동  37.473627  126.938828   9.235526  0.227901     0.239308   9.702734
    21  신림동  37.485691  126.918659   7.029246  0.057297     0.048775   7.135319
    22  상계동  37.658394  127.071138   0.086559  0.480492     0.305428   0.872479
    23  상계동  37.655939  127.066406   0.097205  0.060736     0.214360   0.372301
    24  상계동  37.686659  127.055818   0.263639  0.401524     0.979209   1.644371

In \[55\]:

    # 법정동 별로 sum_dis 값이 가장 큰 행 선택
    max_sum_dis_row = result_df.groupby("법정동")["sum_dis"].idxmax()
    max_sum_dis_df = result_df.loc[max_sum_dis_row]

    # 맵핑을 위한 Latitude와 Longitude 추출
    max_sum_dis_lat = max_sum_dis_df["Latitude"]
    max_sum_dis_lon = max_sum_dis_df["Longitude"]

    # 맵핑 결과 출력
    mapping_result_df = pd.DataFrame({"법정동": max_sum_dis_df["법정동"], "Latitude": max_sum_dis_lat, "Longitude": max_sum_dis_lon})
    print(mapping_result_df)

        법정동   Latitude   Longitude
    13  봉천동  37.474160  126.958181
    24  상계동  37.686659  127.055818
    17  신림동  37.461990  126.918499
    0   화곡동  37.554668  126.854805

In \[56\]:

    import folium

    # 지도 초기화
    map_center_lat = mapping_result_df["Latitude"].mean()
    map_center_lon = mapping_result_df["Longitude"].mean()
    m = folium.Map(location=[map_center_lat, map_center_lon], zoom_start=12)

    # 데이터프레임 순회하며 마커 생성
    for _, row in mapping_result_df.iterrows():
        lat, lon = row["Latitude"], row["Longitude"]
        tooltip = row["법정동"]
        folium.Marker(location=[lat, lon], tooltip=tooltip).add_to(m)

    # 지도 출력
    m

Out\[56\]:

<span style="color:#565656">Make this Notebook Trusted to load map: File
-\> Trust Notebook</span>

In \[ \]: